### PR TITLE
Update README.md with three dependencies packages added.

### PR DESCRIPTION
**Pull request by henrywang**
To avoid compiling dependence issue, openssl-devel and cmake should be installed first.

### CODE REVIEW

**Comment by atodorov** [comment]
@henrywang please rebase to master instead of merging it

**Comment by henrywang** [comment]
Done and thanks Alex!

**Comment by bcl** [comment]
We should probably just make a list, like this:

### Required Host Packages
The host will need to have the following packages installed before building or running the bdcs-api-server
* openssl-devel
* sqlite-devel
* cmake

**Comment by henrywang** [comment]
Updated. Thanks Brian!

**Pull request merged**
