### PR TITLE
Depclose only ids

### PR DESCRIPTION
**Pull request by dashea**
Another big depclose change, wooo.

### CODE REVIEW

**Comment by dashea** [comment]
Flattened the expression (if there's only one item it doesn't need to be Or(vec![thing]) or And(vec![thing]) or whatever), removed duplicates being created where a single package provides itself multiple times (libgcc provides several versions of itself), and added some more tests.

**Comment by dashea** [comment]
I figure I'll wait on https://github.com/weldr/bdcs-api-rs/pull/45 to merge since otherwise I'll make a mess of the test changes.

**Comment by atodorov** [comment]
@dashea can you resolve the conflicts ?  

Also I'd like to have this one merged before #48 and #51 because they will have conflicts as well (allowing unused variables, removing unused imports, etc).

**Comment by dashea** [comment]
Rebased, had to do some things I'm not proud of to make the tests work

**Comment by atodorov** [comment]
I've tried the tests locally and they all pass. Merging b/c already approved and no other comments for a while.

**Pull request merged**
